language: node_js

node_js:
  - 12
  - 14
  - lts/*

branches:
  - master
  - main

install:
  - npm install
  - npm install pm2 -g

stages:
  - Test
  - Build
  - Serve

jobs:
  include:
    - stage: Test
      name: "Client Test"
      script: npm run test:client
    - stage: Build
      name: "Client & Server Build"
      script: npm run build:client
      script: npm run build:server
    - stage: Serve
      name: "Serve By PM2"
      script: npm run pm2
      script: pm2 delete all


after_success:
  - bash <(curl -s https://codecov.io/bash)
