name: Assign To Myself

on: [pull_request_target]

jobs:
  assign:
    runs-on: ubuntu-latest

steps:
      - name: Assign User
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -d '{"assignees": ["linbudu599"]}' \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/assignees
