name: GraphQL-Explorer-Client

on:
  push:
    branches:
      - master
      - main

jobs:
  job1:
    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x, 12.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
         # 额外启用一台使用node14 Ubuntu18的实验任务
          - node-version: 14
            os: ubuntu-18.04
            experimental: true
    timeout-minutes: 360
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Client Tests
        run: npm run test:client
      - name: Client Build
        run: npm run build:client
