name: Deploy To ALi Cloud ECS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Deps
        run: npm i
      - name: Build
        run: npm run build
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SECRET_KEY }}
          ARGS: "-avz --delete"
          # 全拷过去有点笨比其实 但这个action好像不能ignore
          SOURCE: "*"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /usr/local/demo-collections/graphql-explorer-server
