name: Docs-Schema-Generator

on:
  push:
    branches:
      - master

jobs:
  job1:
    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: |
          npm install
      - name: Serve By PM2
        run: npm run pm2
      - name: Generate Documents
        run: npm run gen:docs
      - name: Generate Schema With Type Definition
        run: npm run gen:code
